In [1]:
import pandas as pd
df=pd.read_csv("C:/Users/20424/Desktop/online_retail.csv")
df.head

<bound method NDFrame.head of        InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

                InvoiceDate  UnitPrice  CustomerID         Country
0       2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1       2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2       2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3       2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4       2010-12-01 08:26:00       3.39     17850.0  United Kingdom
...                     ...        ...         ...             ...
541904  2011-12-09 12:50:00       0.85     12680.0          France
541905  2011-12-09 12:50:00       2.10     12680.0          France
541906  2011-12-09 12:50:00       4.15     12680.0          France
541907  2011-12-09 12:50:00       4.15     12680.0          France
541908  2011-12-09 12:50:00       4.95     12680.0          France

[541909 rows x 8 columns]>

In [2]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [4]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
df['UnitPrice'].quantile([0.9,0.95,0.99])

0.90     7.95
0.95     9.95
0.99    18.00
Name: UnitPrice, dtype: float64

In [11]:
df=df.dropna(subset=['CustomerID','Description'])
df=df[(df['UnitPrice']>0) & (df['Quantity']>0) & (df['UnitPrice']<1000)].copy()
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])
df['CustomerID']=df['CustomerID'].astype(int)
df=df.copy()
df.shape

(397863, 8)

In [12]:
df['Revenue']=(df['Quantity']*df['UnitPrice']).round(2)
df[['Quantity','UnitPrice','Revenue']].head()

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34

In [13]:
df['YearMonth']=df['InvoiceDate'].dt.to_period('M')
df['YearMonth']=df['YearMonth'].astype(str)
df['Date']=df['InvoiceDate'].dt.date

In [15]:
print('rows,cols:',df.shape)
print('null check:/n',df.isnull().sum())
print('min Quantity:',df['Quantity'].min())
print('UnitPrice Range:',df['UnitPrice'].min(),'to',df['UnitPrice'].max())
print('unique Customers:',df['CustomerID'].nunique())
print('date range:',df['InvoiceDate'].min(),'to',df['InvoiceDate'].max())

rows,cols: (397863, 11)
null check:/n InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
Revenue        0
YearMonth      0
Date           0
dtype: int64
min Quantity: 1
UnitPrice Range: 0.001 to 908.16
unique Customers: 4337
date range: 2010-12-01 08:26:00 to 2011-12-09 12:50:00

In [18]:
(df['UnitPrice']>500).sum()

np.int64(20)

In [19]:
df.to_csv('C:/Users/20424/Desktop/online_retail_clean.csv',index=False)